### ISSUE TITLE
build jnaerate failed

### ISSUE THREAD

**Issue by yangzp138** [google/mr4c#2]
I tried to build jnaerate object in ant, but failed, see below error message. I have already copied  jna-3.4.0.jar and jnaerator-0.11.jar to java/lib.  Is there any other depended jars jnaerate need? Thanks

jnaerate:

BUILD FAILED
java.lang.NoClassDefFoundError: com.ochafik.lang.jnaerator.parser.Identifier$QualifiedIdentifier
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:237)
        at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:135)
        at org.apache.tools.ant.taskdefs.Java.run(Java.java:764)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:218)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:132)
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:619)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:357)
        at org.apache.tools.ant.Target.performTasks(Target.java:385)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
        at org.apache.tools.ant.Main.runBuild(Main.java:758)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
Caused by: java.lang.ClassNotFoundException: com.ochafik.lang.jnaerator.parser.Identifier$QualifiedIdentifier
        at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1400)
        at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1341)
        at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1094)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:827)
        ... 23 more

**Comment by yangzp138** [comment]
It looks like cased by com.ochafik.lang.jnaerator.JNAerator. what's the purpose of com.ochafik.lang.jnaerator.JNAerator?  How to get it ?

**Comment by mitchwuzhere** [comment]
Closing, this was resolved on the forum:
https://groups.google.com/forum/#!topic/mr4c/ZMx3FnpSQRw
